app_name: recipe-app
app_dir: /opt/recipe-app
app_user: appuser
app_port: 5000

python_bin: python3
nginx_conf_path: /etc/nginx/conf.d/recipe-app.conf
systemd_service_path: /etc/systemd/system/recipe-app.service
